description = "Ubuntu 22.04 Jammy Jellyfish base image with buildpacks for Java, Go, .NET Core, Node.js, Python, Apache HTTPD, NGINX and Procfile"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/dotnet-core:4.9.0"
  version = "4.9.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/go:4.19.26"
  version = "4.19.26"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java-native-image:14.11.0"
  version = "14.11.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java:22.4.0"
  version = "22.4.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/nodejs:10.10.0"
  version = "10.10.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/procfile:5.13.7"
  version = "5.13.7"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/python:2.61.0"
  version = "2.61.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/ruby:3.0.3"
  version = "3.0.3"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/web-servers:4.10.0"
  version = "4.10.0"

[lifecycle]
  version = "0.21.18"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ruby"
    version = "3.0.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core"
    version = "4.9.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go"
    version = "4.19.26"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "14.11.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "22.4.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/web-servers"
    version = "4.10.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "10.10.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "2.61.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.13.7"

[stack]
  build-image = "docker.io/paketobuildpacks/build-jammy-base:0.1.269"
  id = "io.buildpacks.stacks.jammy"
  run-image = "index.docker.io/paketobuildpacks/run-jammy-base:latest"
